### ISSUE TITLE
Expansion filters using fs.stats similar to grunt.file.expand

### ISSUE THREAD

**Issue by bmcminn** [kaelzhang/node-fs-expand#2]
Curious if you had thoughts about adding the `filters` object parameter as a means of filtering the expanded files similarly to how `grunt.file.expand` does?

http://gruntjs.com/api/grunt.file#grunt.file.expand

It's pretty convenient most times I've used it.

**Comment by kaelzhang** [comment]
I'll think about it, that the very original purpose of this package is to provide a `grunt.file.expand`-like method to glob files.
